collections:
  - name: ansible.posix # docker
    version: ">=1.4.0"
  - name: google.cloud
  - name: community.aws
  - name: community.docker
    version: ">=3.0.2"
  - name: containers.podman
  - name: azure.azcollection
    version: ">=1,<2"
  - name: community.crypto
    version: ">=2,<3"
